### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by rmullig2** [learn-co-curriculum/flatiron-bnb-associations#10]
// ♥ bundle exec rspec                                                                                                                   
WARN: Unresolved specs during Gem::Specification.reset:                                                                                  
      activesupport (>= 4.2)                                                                                                             
WARN: Clearing out unresolved specs.                                                                                                     
Please report a bug if this causes problems.                                                                                             
/usr/local/rvm/gems/ruby-2.3.1/gems/bundler-1.13.6/lib/bundler/runtime.rb:40:in `block in setup': You have already activated spring 2.0.0
, but your Gemfile requires spring 1.3.3. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)

**Comment by pickledyamsman** [comment]
@aturkewi this is still an issue with the wrong version of spring in the gemfile. This is happening in the IDE.

**Comment by maxwellbenton** [comment]
Hi @rmullig2,

We updated the Gemfile for this lab early last year and again this Spring and believe this issue is resolved. Thank you for opening this and contributing to a Learn.co lesson!
