### ISSUE TITLE
Spec has an issue

### ISSUE THREAD

**Issue by WerkerM** [learn-co-curriculum/flatiron-bnb-associations#9]
[https://github.com/learn-co-curriculum/flatiron-bnb-associations/blob/e5856f05d1cfa917f66660598c545a757cddfacc/spec/models/city_spec.rb#L34](url)

On lines 20 and 34, 'nyc' had to be changed to new_york_city

**Comment by AnnJohn** [comment]
@pletcher the other issues raised in this lab are all the same as this issue. thanks!
